### ISSUE TITLE
Tab Bar Color

### ISSUE THREAD

**Issue by pkgundam** [melieskubrick/CarbonKitSwift#4]
Hi, thank you for the amazing library?
This is not an issue.
Can you please tell me how do I make the navigation bar and the tab bar control which has all the swipe options the same color, I went through the code but could not find how to set the color for tab bar.

Like this. the background for swipe options has the same color as nav bar.
https://s3.amazonaws.com/cocoacontrols_production/uploads/control_image/image/6057/iOS_Simulator_Screen_Shot_28_Mar_2015_20.42.34.png

Thank you for your help.

**Comment by pkgundam** [comment]
thank you very much for the answer, appreciate it.

**Comment by pkgundam** [comment]
If there are only two tab options, how do I center the tabs to equal width and the title of the tab to be aligned center in each tab

**Comment by melieskubrick** [comment]
in your settings apply:

carbonTabSwipeNavigation.setTabExtraWidth(30)
carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(UIScreen.mainScreen().bounds.size.width/2, forSegmentAtIndex: 0)
carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(UIScreen.mainScreen().bounds.size.width/2, forSegmentAtIndex: 1)
